name: Release new version

on: push

jobs:
  release:
    name: Build and publish new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set current version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.14.0

      - name: Build pipelinit core package
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd core
          deno run --unstable -A package.ts ${{ env.RELEASE_VERSION }}

      - name: Build pipelinit core package publish
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://df77-2804-431-c7ef-1102-bbe3-352e-5343-df64.ngrok.io"
      - run: |
          cd core/npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
