name: Release new version
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PRERELEASE: true

jobs:
  release:
    name: Build and publish new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.14.0
      - name: Build pipelinit core package
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://2325-2804-431-c7ee-c1a1-3cdb-9e8e-9555-b8a2.ngrok.io"
      - run: |
          cd core
          deno run --unstable --allow-read --allow-write --allow-run package.ts
      - run: |
          cd core
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
